#!/usr/bin/env bash

[[ -n ${_ALIASLIB_LOADED:-} ]] && return
readonly _ALIASLIB_LOADED=1

calc_perc() {
    local value="$1"
    local maxmum="$2"

    awk -v v="$value" -v m="$maxmum" 'BEGIN {printf "%.2f\n", (v/m)*100}'
}

byte_unit() {
    local input_value=($(echo "$1" | tr -s '=' ' '))
    local output_type=($(echo "$2" | tr -s '=' ' '))
    local ti to ag va

    ti="${input_value[0]:-0}"
    va="${input_value[1]:-0}"

    ag="${output_type[0]:-0}"
    to="${output_type[1]:-0}"

    if (( ag == "to" )) ;then
        case $to in
            KB)
                ;;
            MB)
                ;;
            GB)
                ;;
        esac
    fi

}
