#!/usr/bin/env bash

[[ -n ${_ALIASLIB_LOADED:-} ]] && return
readonly _ALIASLIB_LOADED=1

# CONTEXTLIB
source "$BASHLIB/contextlib"

alias exit="context-exit"
alias see="context-see"
alias cd="context-cd"
alias rebase="context-rebase"
alias pybuild="python3 -m build"
alias pypi="python3 -m twine upload --verbose dist"
