#!/usr/bin/env bash

[[ -n ${_PS1LIB_LOADED:-} ]] && return
readonly _PS1LIB_LOADED=1



source "$BASHLIB/gitlib"
source "$BASHLIB/ansilib"

ps1_git_info() {
    local status branch

    branch=$(get_curr_branch)
    [ -z "$branch" ] && return

    is_status_ok && status="" || status=""

    echo -e ":󰊢  $(ansi_esc "  ${branch} ${status}" -r1)"
}

tilda() {

    # to fix the proble with (\w) and scape
    # use this and create the path manually
    local state=0
    local parts=()
    local part

    # split the path into (var home  user ...)
    # and build as after user name -> /var/home/user/ -> ~/
    for part in ${PWD//\// }; do
        if [[ $state -eq 1 ]]; then
            parts+=("$part")
        elif [[ $state -eq 0 && $part == "$USER" ]]; then
            state=1
            parts+=("~")
        fi
    done

    local IFS="/"
    echo "${parts[*]}"
}


build_ps1() {
    local msg="\n   $(ansi_esc "$(tilda)" -c1)"

    if [ -n "$VIRTUAL_ENV" ]; then
        local venv_name="${VIRTUAL_ENV_PROMPT:-NONE}"
        msg+=" $(ansi_esc " (${venv_name// /})" -g1)"
    fi

    is_git_repo && msg+="$(ps1_git_info)"
    PS1="${msg}\n   "
}
