#!/usr/bin/env bash

[[ -n ${_BASHRC_LOADED:-} ]] && return
readonly _BASHRC_LOADED=1


export MOZ_ENABLE_WAYLAND=1

# ALIASES
source "$BASHLIB/aliaslib"

# PS1
source "$BASHLIB/ps1lib"

export PROMPT_COMMAND=build_ps1

export PATH="$HOME/.local/bin:$PATH"
